# Configuration for POC Chat System
# Sensitive values should be set via environment variables (see .env.example)

openrouter:
  # API credentials are loaded from environment variables
  # OPENROUTER_API_KEY and OPENROUTER_BASE_URL
  
  # LLM for event classification (JSON output)
  classification:
    model: "google/gemini-2.5-flash-lite"
    temperature: 0.1
    max_tokens: 1000
  
  # LLM for chat response generation (text output)
  response:
    model: "google/gemini-2.5-flash-lite"
    temperature: 0.7
    max_tokens: 2000
  
memory:
  # Redis connection loaded from REDIS_URL environment variable
  sm_ttl: 240 # SM TTL in seconds (4 minutes)
  lm_base_path: "data/longterm" # Base path for LM JSON files
  extend_ttl_on_activity: true # Extend TTL when users send messages to keep active conversations alive

# NLU Configuration for intent/entity detection
nlu:
  # Intent configuration for Thai computer sales
  default_intent: "greet:0.3, purchase_intent:0.8, inquiry_intent:0.7, support_intent:0.6, complain_intent:0.6"
  additional_intent: "complaint:0.5, cancel_order:0.4, ask_price:0.6, compare_product:0.5"
  
  # Entity configuration for computer sales domain
  default_entity: "product, quantity, brand, price"
  additional_entity: "color, model, spec, budget, warranty, delivery"
  
  # Delimiter configuration for parsing
  tuple_delimiter: "<||>"
  record_delimiter: "##"
  completion_delimiter: "<|COMPLETE|>"
  
  # Parser settings
  enable_robust_parsing: true
  importance_threshold: 0.35 # Lowered threshold for simplified scoring system - allows more business messages through